# The placeholder version string will be replaced at build time by
# the runBuildPrep.sh script

apiVersion: v1
description: "Kubernetes resources for cray-crus"
name: "cray-crus"
home: "scms/cray-crus"
version: @VERSION@
