# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
#
# The placeholder 0.0.0-* version string(s) will be replaced at build time by
# the runBuildPrep.sh script in the cms-meta-tools repo
#
cray-service:
  type: Deployment
  nameOverride: cray-crus
  serviceAccountName: "cray-crus-actor"
  containers:
    cray-crus:
      name: cray-crus
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-crus
        tag: 0.0.0-image
        pullPolicy: IfNotPresent
      env:
        - name: CRUS_CONFIGURATION
          value: "prod"

      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"

      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 8080
          path: /session
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          port: 8080
          path: /session
        initialDelaySeconds: 5
        periodSeconds: 3

    cray-crua:
      name: cray-crua
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-crus
        tag: 0.0.0-image
        pullPolicy: IfNotPresent
      env:
        - name: CRUS_CONFIGURATION
          value: "prod"
        - name: BOOT_SESSION_URI
          value: "http://cray-bos/v1/session"
        - name: CRUS_NODE_GROUP_URI
          value: "http://cray-smd/hsm/v1/groups"
        - name: CRUS_BSS_HOSTS_URI
          value: "http://cray-bss/boot/v1/hosts"
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      command:
        - "/bin/sh"
        - "-c"
        - "/app/entrypoints/controller.sh"
      livenessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "ps -ef | grep controller.sh"
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "ps -ef | grep controller.sh"
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - mountPath: /etc/slurm
          name: slurm-config
        - mountPath: /var/run/munge
          name: munge-rundir
        - name: munge-key
          mountPath: /munge

    munge:
      name: munge
      image:
        repository: arti.dev.cray.com/wlm-slurm-docker-master-local/munge-munge
        tag: 1.1.2-20220210194015_e8cc1ca
        pullPolicy: IfNotPresent
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      livenessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "munge -n | unmunge"
        initialDelaySeconds: 30
        periodSeconds: 30
        failureThreshold: 3
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "mount | grep ' /munge ' && mount | grep '/run/munge '"
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - mountPath: /munge
          name: munge-key
        - mountPath: /var/run/munge
          name: munge-rundir

  volumes:
    slurm-config:
      name: slurm-config
      configMap:
        defaultMode: 420
        name: slurm-map

    munge-key:
      name: munge-key
      secret:
        defaultMode: 420
        secretName: munge-secret

    munge-rundir:
      name: munge-rundir
      emptyDir: {}
  ingress:
    enabled: true
    uri: /

  etcdCluster:
    enabled: true
    pvc:
      storage: 8Gi
    compactionMode: revision
    compactionRetention: "100000"
    snapshotMax: "1"
    snapshotCount: "5000000"
    heartbeatInterval: "4200"
    enforceAntiAffinity: "21000"
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 10m
        memory: 64Mi
