---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cray-crus-actor
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-crus-actor
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-crus-actor
subjects:
  - kind: ServiceAccount
    name: cray-crus-actor
    namespace: services
roleRef:
  kind: Role
  name: cray-crus-actor
  apiGroup: rbac.authorization.k8s.io
